name: Dependency Submission
on:
  push:
    branches:
      - master


permissions:
  contents: write


env:
  JDK_VERSION: "22"


jobs:
  submit-dependencies:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: "temurin"
          java-version: ${{ env.JDK_VERSION }}

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"